### ISSUE TITLE
Sponsorship Popup Does Not Center To User's View

### ISSUE THREAD

**Issue by sabjorn** [sabjorn/BandcampEnhancementSuite#106]
The popup shows in the centre of the top of the screen. Which means, if you are far down the page because you have many tracks in your cart, you don't actually know why you can't progress towards paying.

solution:
setup the popup to be in the centre of the user's view not the centre of the top of the page

**Comment by sabjorn** [comment]
@emcniece any suggestions?

**Comment by emcniece** [comment]
Try adding a wrapper div outside of `bes_dialog` and give it a fixed position. Something like:

```html
<div id="bes_wrapper">
  <div id="bes_dialog">...</div>
</div>

<style>
#bes_wrapper {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
}
</style>
```

That should get it to stay within viewport regardless of scroll position.

**Comment by sabjorn** [comment]
closed with: fix/106_popup_not_centered
