### ISSUE TITLE
Cart Recollection

### ISSUE THREAD

**Issue by sabjorn** [sabjorn/BandcampEnhancementSuite#127]
Sometimes errors happen that cause the cart to disappear (never to return).
If we cash the **session id** (from cookie), we can force Bandcamp to reload it.

In the future this might mean a dropdown of previous carts (could be an issue if you've already paid for everything) or at least store the last cart and provide a way to access that history.

Exporting might be interesting too as long as the **session id** isn't responsible for user verification in some way (don't want to be sharing logged in sessions)

**Comment by emcniece** [comment]
Sometimes session generation is done using browser fingerprinting and generating a hash of several variables, like the username or timestamp or browser user agent. Sometimes apps will invalidate sessions if one of these variables changes when regenerating a hash.

Might be worth testing this to see if BC will invalidate session when these things change - an easy way to test might be to paste a session from Chrome into Firefox to see if it reloads a cart.

**Comment by sabjorn** [comment]
@emcniece just checked loading a session_id from Chrome in Firefox. No issue at all.

**Comment by sabjorn** [comment]
not going to implement
