### ISSUE TITLE
Firefox link in README

### ISSUE THREAD

**Issue by shmup** [sabjorn/BandcampEnhancementSuite#163]
I don't know if you actually manage the FF extension, thought it does link back to this repo:

https://addons.mozilla.org/en-US/firefox/addon/bandcamp-enhancement-suite/

But, could you also link to it in the README giving it a bit of credibility? I'd make a PR, but there may be a reason for not listing it

**Comment by sabjorn** [comment]
@shmup oh! totally. I'll add now. Thanks for the feedback!

**Comment by sabjorn** [comment]
done with 8435c2016258cde73d224d1af43ddd559793ac14
