### ISSUE TITLE
Dragbar resize width of preview iframe

### ISSUE THREAD

**Issue by sabjorn** [sabjorn/BandcampEnhancementSuite#17]
The iframe width is too narrow (but looks good). 

Adding something like this: https://stackoverflow.com/questions/6219031/how-can-i-resize-a-div-by-dragging-just-one-side-of-it

would allow users to change the iframe window width easily when desired.

**Comment by sabjorn** [comment]
this may be another option (I like the look):

https://stackoverflow.com/questions/46931103/making-a-dragbar-to-resize-divs-inside-css-grids

**Comment by emcniece** [comment]
Interesting idea!

- What should the default width be?
- At what point (if any) should the iframe automatically resize?
- Should iframe width be remembered?
- Should iframe width be "global" or defined in an options page?

**Comment by sabjorn** [comment]
* I think the current default width is fine. Unfortunately the resolution play bar for the player is a function of the width of the player. So, while it would be nice to have the frame narrower than it is currently to make it work with layout of the page (have the player be the same width as the album), it just doesn't seem worth fumbling around.
* I think no auto resize
* no and yes? (see the next answer)
* yes, this is probably the best solution in general. saving a default after resizing one window would be great but initially I think just user setting would be amazing (maybe even more useful than resizing with the mouse, unless we show the pixels for them?)

**Comment by sabjorn** [comment]
closing this because the future Player/Playlist feature will completely remove the need for this
