### ISSUE TITLE
Uncaught Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by emcniece** [sabjorn/BandcampEnhancementSuite#175]
Error encountered after having a page (https://genomrecords.bandcamp.com/) open for a long time:

```
[j](main.js:21 Uncaught Error: Attempting to use a disconnected port object)
    at i.boxClicked (main.js:21:78098)
    at HTMLButtonElement.<anonymous> (main.js:21:80547)
```

This appears when clicking the preview history button, which no longer toggles. Might be worth trying a reconnection attempt when catching this error.

**Comment by sabjorn** [comment]
haven't come across this -- going to close for now and will re-open if it happens again
