### ISSUE TITLE
repeat and shuffle option when playing an album

### ISSUE THREAD

**Issue by BatmanDrinkingLean** [sabjorn/BandcampEnhancementSuite#176]
button to repeat/loop an album after it finishes, shuffling an album would also be cool.

**Comment by BatmanDrinkingLean** [comment]
i would totally enjoy the implementation of these features

**Comment by sabjorn** [comment]
@BatmanDrinkingLean thanks for the suggestions but this set of features isn't really in line with the intended goal of the extension -- which is to make it easier for DJs to find music -- not to improve the casual listening experience of Bandcamp.

Hopefully there is an extension out there that does what you need. Good luck :D
