### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by sabjorn** [sabjorn/BandcampEnhancementSuite#54]
Didn't want to get into Git Projects yet so I'm just making an issue as a way to track what's remaining for this release.

1. Update Readme with new features (volume, keyboard control, and mouse clicking)
2. https://github.com/sabjorn/BandcampEnhancementSuite/issues/52
3. screenshot for volume control and mouse clicking

**Comment by emcniece** [comment]
Could use milestones in lieu of a project?

**Comment by sabjorn** [comment]
@emcniece 
RC is submitted for publishing:

https://github.com/sabjorn/BandcampEnhancementSuite/releases/tag/1.1.0rc1
