### ISSUE TITLE
extension doesn't work for custom urls

### ISSUE THREAD

**Issue by marl64** [sabjorn/BandcampEnhancementSuite#77]
i imagine this would be pretty straightforward to add support for

**Comment by sabjorn** [comment]
@marl64 I feel this one very much. It bugs me all the time.

However, this is actually a bit complicated. Chrome Extensions require explicit domain permissions.

Looking in the manifest:
https://github.com/sabjorn/BandcampEnhancementSuite/blob/3ec82b21bbfd2f96f04b103a83c2463a7170534c/manifest.json#L19-L23

you will see a couple of domains (including some with `*` wildcards).

IT IS possible to set the permissions to have all domains BUT there is a very real possibility that the plugin will get rejected from publication if it's set for all URLs. 

I will keep this issue open to remind me to try for the next release BUT likely very limited by Google itself.

**Comment by sabjorn** [comment]
@marl64 also, I appreciated that you would join Github to submit this issue :D
